Repository pistacheio/pistache, pull requests merged in 2023-11, with the labels that each got.

#1158 fix: File descriptor leaks for eventfd and timerfd_create
  include/pistache/os.h
  src/common/os.cc
  src/server/endpoint.cc
  tests/CMakeLists.txt
  tests/helpers/CMakeLists.txt
  tests/helpers/fd_utils.cc
  tests/helpers/fd_utils.h
  tests/helpers/meson.build
  tests/helpers_test.cc
  tests/http_server_test.cc
  tests/meson.build
  version.txt
Labels: bug, fix in progress, security

#1170 Support identity content encoding for setCompression(). Fixes #1169...
  src/common/http.cc
  version.txt
Labels: bug, fix in progress

#1152 debian/control: Build with deflate content encoding enabled by default...
  changelog
  control
  rules
Labels: enhancement, fix in progress

#1173 Fixes #1172, missing zlib headers during binary package build...
  control
Labels: bug, fix in progress

#1175 Fix for #1174, armhf builds broke with new compression code...
  src/common/http.cc
  version.txt
Labels: bug, portability, fix in progress
