Repository pistacheio/pistache, pull requests merged in 2023-07, with the labels that each got.

#1136 Add support for custom headers with dash in their names
  include/pistache/http_header.h
  tests/headers_test.cc
  version.txt
Labels: enhancement, fix in progress

#1140 refactor!: switch to sockaddr_storage, IPv6 and resolver improvements
  .github/workflows/linux.yaml
  include/pistache/client.h
  include/pistache/http_header.h
  include/pistache/net.h
  meson.build
  src/client/client.cc
  src/common/http_header.cc
  src/common/net.cc
  src/server/listener.cc
  tests/http_server_test.cc
  tests/net_test.cc
  version.txt
Labels: bug, refactor, security

#1145 Make rapidjson dependency optional
  include/pistache/meson.build
  meson.build
  meson_options.txt
  version.txt
Labels: bug, refactor, fix in progress

#1151 Partial fix for #1148 by adding deflate content encoding support...
  README.md
  include/pistache/http.h
  include/pistache/http_header.h
  include/pistache/http_headers.h
  meson.build
  meson_options.txt
  src/common/http.cc
  src/common/http_header.cc
  src/common/http_headers.cc
  src/meson.build
  tests/http_server_test.cc
  version.txt
Labels: enhancement, performance, fix in progress
