Repository pistacheio/pistache, pull requests merged in 2024-10, with the labels that each got.

#1252 Avoid using compiler.has_function('dladdr')
  meson.build
  version.txt
Labels: bug, portability, fix in progress

#1256 Make linux.yaml workflow work for debian:testing/clang
  .github/workflows/linux.yaml
  version.txt
Labels: bug, portability, fix in progress, dependencies, unit / CI testing

#1255 fix: missing destructor call in Pistache::Queue
  include/pistache/mailbox.h
  tests/mailbox_test.cc
  version.txt
Labels: bug, fix in progress, security

#1251 fix: buffer overflow with strtol
  src/common/http.cc
  src/common/http_header.cc
  tests/fuzzers/fuzz_parser.cpp
  tests/headers_test.cc
  version.txt
Labels: bug, fix in progress, security
