Repository pistacheio/pistache, pull requests merged in 2024-04, with the labels that each got.

#1199 Queue pop-entry fix
  include/pistache/mailbox.h
  tests/http_server_test.cc
  version.txt
Labels: bug, fix in progress

#1204 Streaming test - Avoid memory-leak github test failure report
  tests/listener_test.cc
  tests/request_size_test.cc
  tests/streaming_test.cc
  version.txt
Labels: bug, performance, fix in progress, security

#1191 Improve fuzzer
  .reuse/dep5
  tests/fuzzers/corpus/http-1.txt
  tests/fuzzers/corpus/http-10.txt
  tests/fuzzers/corpus/http-11.txt
  tests/fuzzers/corpus/http-12.txt
  tests/fuzzers/corpus/http-13.txt
  tests/fuzzers/corpus/http-14.txt
  tests/fuzzers/corpus/http-15.txt
  tests/fuzzers/corpus/http-16.txt
  tests/fuzzers/corpus/http-17.txt
  tests/fuzzers/corpus/http-18.txt
  tests/fuzzers/corpus/http-2.txt
  tests/fuzzers/corpus/http-3.txt
  tests/fuzzers/corpus/http-4.txt
  tests/fuzzers/corpus/http-5.txt
  tests/fuzzers/corpus/http-6.txt
  tests/fuzzers/corpus/http-7.txt
  tests/fuzzers/corpus/http-8.txt
  tests/fuzzers/corpus/http-9.txt
  tests/fuzzers/fuzz_parser.cpp
  version.txt
Labels: enhancement, fix in progress, security

#1210 fix(peer.cc) compile warning for implicitly deleted default constructor
  src/common/peer.cc
  version.txt
Labels: bug, fix in progress

#1209 fix(server): Crash if remove not existing route
  .reuse/dep5
  src/server/router.cc
  tests/fuzzers/corpus/151a3cba089a89c9d1407ffe08e66f5807206d4f
  tests/fuzzers/corpus/1a123ecb986602e7a63ad85805ad1b0fa68d7c20
  tests/fuzzers/corpus/225aa589c4433f4dddf110306aeb1d7daa08d94c
  tests/fuzzers/corpus/2d8d49508cc1400610e846490e092f5b42b7798b
  tests/fuzzers/corpus/337a82e18ae0918c54607da0510111ecae14c5af
  tests/fuzzers/corpus/3d744c1c4d7c10bd34b2ffc53104b736059d629e
  tests/fuzzers/corpus/6a632298ac9ea6e05267892d3eb608e0c06d9759
  tests/fuzzers/corpus/746dbfb89b36785075b80569064a1654be613f47
  tests/fuzzers/corpus/75952bb79d780fafa553c1a0bdddc9629cef88f2
  tests/fuzzers/corpus/8165d5b7e7fe7c2952955c6618565316649c38c2
  tests/fuzzers/corpus/83e59c3a4c183f1f88678605e15da3aa568e3b59
  tests/fuzzers/corpus/96607ea4447e4d6c28b00990ddec0ee0500955b5
  tests/fuzzers/corpus/abfa7b63b7e37a2d992b53c76b7785c1af6ac595
  tests/fuzzers/corpus/ac5f7a18fa9411453d5bd02978f667d7414876bf
  tests/fuzzers/corpus/ad71f85838f68e0779de86398faa910d2ce0b229
  tests/fuzzers/corpus/d7e60042b9c7b4bb905fa6eef2ae3609413dd046
  tests/fuzzers/corpus/f0c1aa1b78c96efd2b4e57f989c631b373333791
  tests/fuzzers/corpus/f95881a2e895c9f007152c6c84e7b3d399c24a65
  tests/fuzzers/corpus/fd57d162e86cdf4ca56f780a8280d5e5aa327b58
  tests/fuzzers/fuzz_parser.cpp
  tests/router_test.cc
  version.txt
Labels: bug, security
