Repository pistacheio/pistache, pull requests merged in 2024-12, with the labels that each got.

#1268 Fix errno include error
  include/pistache/common.h
  include/pistache/eventmeth.h
  include/pistache/listener.h
  include/pistache/mailbox.h
  include/pistache/net.h
  include/pistache/pist_check.h
  include/pistache/pist_timelog.h
  include/pistache/ps_basename.h
  include/pistache/pst_errno.h
  include/pistache/timer_pool.h
  include/pistache/transport.h
  include/pistache/winornix.h
  src/client/client.cc
  src/common/eventmeth.cc
  src/common/http.cc
  src/common/http_defs.cc
  src/common/http_header.cc
  src/common/net.cc
  src/common/os.cc
  src/common/peer.cc
  src/common/pist_check.cc
  src/common/pist_strerror_r.cc
  src/common/pist_syslog.cc
  src/common/pist_timelog.cc
  src/common/reactor.cc
  src/common/stream.cc
  src/common/transport.cc
  src/common/utils.cc
  src/server/endpoint.cc
  src/server/listener.cc
  tests/helpers_test.cc
  tests/listener_test.cc
  tests/net_test.cc
  tests/tcp_client.h
Labels: bug, fix in progress

#1269 Remove macOS 12 Scenarios from GitHub Runner macos.yaml
  .github/workflows/macos.yaml
  version.txt
Labels: bug, unit / CI testing

#1270 Fix: Enable use of subproject httplib in macOS despite nofallback
  bldscripts/nfbmesbuild.sh
  tests/meson.build
  version.txt
Labels: bug, portability, dependencies

#1271 C++23 aligned storage
  include/pistache/async.h
  include/pistache/mailbox.h
  version.txt
Labels: enhancement

#1226 C++20 compatibility
  examples/http_server.cc
  include/pistache/async.h
  include/pistache/date_wrapper.h
  include/pistache/http.h
  include/pistache/meson.build
  include/pistache/transport.h
  meson.build
  src/client/client.cc
  src/common/description.cc
  src/common/http.cc
  src/common/http_defs.cc
  src/common/reactor.cc
  src/server/endpoint.cc
  src/server/listener.cc
  tests/cookie_test.cc
  tests/cookie_test_2.cc
  tests/headers_test.cc
  version.txt
Labels: refactor, portability, fix in progress

#1272 Fix: Extended the homebrew Httplib Nofallback Workaround to Linux
  tests/meson.build
  version.txt
Labels: portability, dependencies, unit / CI testing

#1273 ci: Keep GitHub Actions up to date with GitHub's Dependabot
  .github/dependabot.yml
  .github/workflows/linux.yaml
Labels: dependencies, unit / CI testing

#1275 Brew formula
  .github/workflows/brew.yaml
  .gitignore
  Building on macOS.txt
  README.md
  homebrew/pistache.rb
  homebrew/runformula.sh
  tests/meson.build
  tests/rest_server_test.cc
  tests/rest_swagger_server_test.cc
  tests/router_test.cc
  version.txt
Labels: portability
