Repository pistacheio/pistache, pull requests merged in 2024-08, with the labels that each got.

#1225 build: make rapidjson_dep a public dependency
  meson.build
  src/meson.build
Labels: bug, fix in progress, dependencies

#1221 BSD Support (FreeBSD, OpenBSD and NetBSD)
  .clang-format-ignore
  Building on BSD - FreeBSD, OpenBSD and NetBSD.txt
  bldscripts/mesdebugflibevsetdirvars.sh
  bldscripts/mesdebugsetdirvars.sh
  bldscripts/mesflibevsetdirvars.sh
  bldscripts/messetdirvars.sh
  bldscripts/messetdirvarsfinish.sh
  include/pistache/emosandlibevdefs.h
  include/pistache/eventmeth.h
  include/pistache/meson.build
  include/pistache/os.h
  include/pistache/peer.h
  include/pistache/pist_timelog.h
  include/pistache/transport.h
  meson.build
  src/client/client.cc
  src/common/eventmeth.cc
  src/common/http.cc
  src/common/http_defs.cc
  src/common/peer.cc
  src/common/reactor.cc
  src/common/transport.cc
  src/server/listener.cc
  tests/headers_test.cc
  tests/helpers/fd_utils.cc
  tests/http_server_test.cc
  tests/listener_test.cc
  tests/rest_server_test.cc
  version.txt
Labels: bug, enhancement, portability, fix in progress

#1232 build: properly handle public dependencies
  meson.build
  src/meson.build
Labels: bug, dependencies

#1233 macOS Github Workflow
  .github/workflows/macos.yaml
  version.txt
Labels: portability, fix in progress, experimental

#1235 Add Accept header serialization
  include/pistache/http_header.h
  src/common/http_header.cc
  tests/headers_test.cc
  version.txt
Labels: enhancement, fix in progress

#1237 Fix: Lock interest_mutex_ When interest_ Modified in ctlEx
  src/common/eventmeth.cc
  version.txt
Labels: bug, fix in progress
