Repository pistacheio/pistache, pull requests merged in 2024-09, with the labels that each got.

#1146 build: set soname to major.minor
  README.md
  src/CMakeLists.txt
  src/meson.build
Labels: portability, fix in progress

#1229 Fix: In Reactor Add A Mutex To Protect HandlerList Internal Array
  include/pistache/os.h
  src/common/reactor.cc
  src/server/listener.cc
  version.txt
Labels: bug, fix in progress, security, experimental

#1239 fix: data race in Pistache::Rest::Router::route
  include/pistache/router.h
  src/server/router.cc
  version.txt
Labels: bug, fix in progress, security

#1244 Fix compilation error with clang++ 19
  include/pistache/async.h
  version.txt
Labels: bug, fix in progress

#1245 Make dl library dependency
  meson.build
  version.txt
Labels: bug, portability, fix in progress

#1246 Fix: Improved Fix For Issue When dladdr not in libc
  meson.build
  version.txt
Labels: bug, portability, fix in progress
