Repository pistacheio/pistache, pull requests merged in 2025-05, with the labels that each got.

#1310 fix(security,tls): handle no SSL/TLS shutdown from peer in server
  .github/workflows/macos.yaml
  include/pistache/peer.h
  src/common/transport.cc
  subprojects/dump2def/meson.build
  tests/https_server_test.cc
  version.txt
Labels: bug, security

#1315 Fix: Allow Unparseable Pages Returned from AOL Search in Test
  .github/workflows/macos.yaml
  tests/https_client_test_net.cc
  version.txt
Labels: bug, fix in progress, unit / CI testing

#1314 Fix: Update Convenience Build Scripts for OpenSLL libcurl on macOS
  bldscripts/helpers/ifmacOScheckLibcurl.sh
  bldscripts/mesbuild.sh
  bldscripts/mesbuilddebug.sh
  version.txt
Labels: bug, portability, fix in progress, security, unit / CI testing, macOS
