Repository pistacheio/pistache, pull requests merged in 2025-01, with the labels that each got.

#1277 Fix: Adjust Setup PowerShell Scripts to Run on Barebones Windows
  Building on Windows.txt
  src/winlog/installmanatinstall.ps1
  tests/meson.build
  version.txt
  winscripts/gccsetup.ps1
  winscripts/helpers/commonsetup.ps1
  winscripts/msvcsetup.ps1
Labels: enhancement, portability

#1278 Fix: Set PKG_CONFIG_PATH when vcpkg NOT newly installed
  version.txt
  winscripts/helpers/commonsetup.ps1
Labels: bug, Windows

#1282 Fix: In rest_server_test Allow "view-localhost" hostname
  tests/rest_server_test.cc
  version.txt
Labels: bug, portability, unit / CI testing, Windows

#1283 Fix: Use "--force" Option on Visual Studio Install
  version.txt
  winscripts/helpers/commonsetup.ps1
Labels: bug, dependencies, Windows

#1284 Fix: Use ByPass ExecutionPolicy when Invoking installman.ps1
  src/meson.build
  version.txt
Labels: bug, Windows

#1286 meson: check for availability of dladdr
  meson.build
Labels: refactor, portability
